export type UserRole =
  | 'ADMIN'
  | 'HEALTH_OFFICER'
  | 'FACILITY_ADMIN'
  | 'BHW'
  | 'HOSPITAL_ENCODER'
  | 'PHYSICIAN'
  | 'NURSE'
  | 'MIDWIFE';
export type DiseaseCategory =
  | 'VECTOR_BORNE'
  | 'WATER_BORNE'
  | 'AIRBORNE'
  | 'DIRECT_CONTACT'
  | 'OTHER';
export type CaseStatus = 'SUSPECTED' | 'PROBABLE' | 'CONFIRMED';
export type CaseOutcome = 'ONGOING' | 'RECOVERED' | 'DIED';
export type CaseSource = 'PUBLIC_HOSPITAL' | 'PRIVATE_HOSPITAL' | 'RHU' | 'BHW';
export type Sex = 'MALE' | 'FEMALE';
export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH';
export type AlertStatus = 'ACTIVE' | 'RESOLVED' | 'DISMISSED';
export type FeedbackThreadStatus = 'OPEN' | 'CLOSED';

/** Standard API response envelope returned by every endpoint. */
export interface ApiResponse<T> {
  success: boolean;
  message: string;
  data: T;
}

export interface PaginationMeta {
  page: number;
  limit: number;
  total: number;
  pages: number;
}

export interface Paginated<T> {
  items: T[];
  pagination: PaginationMeta;
}

export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: UserRole;
  barangayId?: string | null;
  facilityId?: string | null;
  licenseNo?: string | null;
  providerType?: string | null;
  isActive: boolean;
  barangay?: Barangay | null;
  facility?: Facility | null;
  createdAt?: string;
}

export interface Barangay {
  id: string;
  name: string;
  code: string;
  municipality: string;
  province: string;
  population?: number | null;
  _count?: {
    users?: number;
    cases?: number;
    reports?: number;
    alerts?: number;
  };
}

export interface Disease {
  id: string;
  name: string;
  code: string;
  category: DiseaseCategory;
  description?: string | null;
  isNotifiable: boolean;
  isActive: boolean;
  color?: string | null;
  seasonalMonths: number[];
  caseThreshold: number;
  spikePercentage: number;
  _count?: { cases?: number; alerts?: number };
}

export interface Case {
  id: string;
  diseaseId: string;
  barangayId: string;
  reportedBy: string;
  dateReported: string;
  onsetDate?: string | null;
  age: number;
  ageGroup: string;
  sex?: Sex | null;
  status: CaseStatus;
  outcome: CaseOutcome;
  source: CaseSource;
  notes?: string | null;
  disease?: Disease;
  barangay?: Barangay;
  reporter?: Pick<User, 'id' | 'firstName' | 'lastName' | 'email'>;
  patient?: Pick<Patient, 'id' | 'patientCode' | 'firstName' | 'lastName'>;
  autoGenerated?: boolean;
  patientId?: string | null;
}

export interface RiskReport {
  id: string;
  barangayId: string;
  reportedBy?: string | null;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  source: 'STAFF' | 'RESIDENT';
  category: 'VECTOR_BORNE' | 'WATER_BORNE' | 'AIRBORNE';
  dateReported: string;
  submittedByName?: string | null;
  submittedByContact?: string | null;
  reviewedAt?: string | null;
  rejectionReason?: string | null;
  stagnantWater: boolean;
  poorWasteDisposal: boolean;
  cloggedDrainage: boolean;
  housingCongestion: boolean;
  unsafeWaterSource: boolean;
  poorSanitation: boolean;
  openDefecation: boolean;
  foodContamination: boolean;
  overcrowding: boolean;
  poorVentilation: boolean;
  activeRespiratoryCase: boolean;
  photoUrl?: string | null;
  notes?: string | null;
  barangay?: Barangay;
  reporter?: Pick<User, 'id' | 'firstName' | 'lastName' | 'email'> | null;
  reviewer?: Pick<User, 'id' | 'firstName' | 'lastName' | 'email'> | null;
}

export interface Alert {
  id: string;
  barangayId: string;
  diseaseId?: string | null;
  createdBy?: string | null;
  title: string;
  message: string;
  riskLevel: RiskLevel;
  status: AlertStatus;
  triggeredAt: string;
  resolvedAt?: string | null;
  metadata?: string | null;
  barangay?: Barangay;
  disease?: Disease | null;
}

export interface FeedbackMessage {
  id: string;
  threadId: string;
  senderId: string;
  body: string;
  readAt?: string | null;
  createdAt: string;
  sender?: Pick<User, 'id' | 'firstName' | 'lastName' | 'email' | 'role'>;
}

export interface FeedbackThread {
  id: string;
  subject: string;
  barangayId: string;
  createdById: string;
  status: FeedbackThreadStatus;
  lastMessageAt: string;
  createdAt: string;
  updatedAt: string;
  barangay?: Barangay;
  creator?: Pick<User, 'id' | 'firstName' | 'lastName' | 'email' | 'role'>;
  messages?: FeedbackMessage[];
  latestMessage?: FeedbackMessage | null;
  unreadCount?: number;
  _count?: { messages: number };
}

export interface DashboardStats {
  totalCases: number;
  currentMonthCases: number;
  previousMonthCases: number;
  caseIncrease: number;
  currentWeekCases: number;
  previousWeekCases: number;
  weekCaseIncrease: number;
  currentWeekReports: number;
  previousWeekReports: number;
  weekReportIncrease: number;
  totalBarangays: number;
  totalDiseases: number;
  activeAlerts: number;
  totalReports: number;
}

export interface WeeklyTrend {
  week: string;
  cases: number;
  reports: number;
}

export interface CaseTrend {
  month: string;
  year: number;
  monthNumber: number;
  cases: number;
}

export interface BarangayRanking {
  id: string;
  name: string;
  code: string;
  municipality: string;
  province: string;
  caseCount: number;
  reportCount: number;
  activeAlerts: number;
  riskScore: number;
}

export interface DiseaseBreakdown {
  diseaseId: string;
  name: string;
  code: string;
  color?: string | null;
  caseCount: number;
}

export interface BarangayCaseData {
  id: string;
  name: string;
  code: string;
  municipality: string;
  province: string;
  caseCount: number;
  population: number;
}

export interface PredictionModelInfo {
  name: string;
  trainedOnMonths: number;
  seasonal: boolean;
}

export interface PredictionPoint {
  label: string;
  cases: number;
}

export interface ForecastPoint extends PredictionPoint {
  lower: number;
  upper: number;
}

export interface PredictionSummary {
  nextMonthCases: number;
  trend: 'increasing' | 'decreasing' | 'stable';
  thresholdBreach: boolean;
  caseThreshold: number | null;
}

export interface PredictionResult {
  model: PredictionModelInfo;
  historical: PredictionPoint[];
  forecast: ForecastPoint[];
  summary: PredictionSummary;
  disclaimer: string;
}

export interface BarangayForecast {
  id: string;
  name: string;
  predictedCases: number;
  lower: number;
  upper: number;
  trend: 'increasing' | 'decreasing' | 'stable';
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH';
}

// ---------------------------------------------------------------------------
// EMR (Electronic Medical Record) types
// ---------------------------------------------------------------------------
export type EncounterType = 'CONSULT' | 'PRENATAL' | 'IMMUNIZATION' | 'TB' | 'NCD' | 'FOLLOWUP';
export type DiagnosisCertainty = 'SUSPECTED' | 'PROBABLE' | 'CONFIRMED';
export type CivilStatus = 'SINGLE' | 'MARRIED' | 'WIDOWED' | 'SEPARATED' | 'OTHER';
export type ProblemStatus = 'ACTIVE' | 'RESOLVED' | 'INACTIVE';
export type AllergySeverity = 'MILD' | 'MODERATE' | 'SEVERE';
export type LabStatus = 'ORDERED' | 'RESULTED' | 'CANCELLED';
export type MedicationStatus = 'ACTIVE' | 'DISCONTINUED';
export type MedicalHistoryCategory = 'PMH' | 'SURGICAL' | 'FAMILY' | 'SOCIAL';

export interface PatientIdentifier {
  system: 'PHILHEALTH' | 'PHILSYS' | 'LOCAL' | 'OTHER';
  value: string;
  use?: 'OFFICIAL' | 'SECONDARY' | null;
}

export interface Patient {
  id: string;
  patientCode: string;
  identifiers?: PatientIdentifier[];
  firstName: string;
  middleName?: string | null;
  lastName: string;
  birthDate: string;
  sex: Sex;
  civilStatus?: CivilStatus | null;
  contactNumber?: string | null;
  address?: string | null;
  barangayId?: string | null;
  homeFacilityId?: string | null;
  userId?: string | null;
  philhealthNo?: string | null;
  bloodType?: string | null;
  consentGiven: boolean;
  consentDate?: string | null;
  registeredById?: string | null;
  registeredBy?: Pick<User, 'id' | 'firstName' | 'lastName' | 'role'> | null;
  isActive: boolean;
  notes?: string | null;
  createdAt?: string;
  updatedAt?: string;
  barangay?: Barangay | null;
  homeFacility?: Facility | null;
  encounters?: Encounter[];
  allergies?: Allergy[];
  problems?: Problem[];
  immunizations?: Immunization[];
  maternalRecords?: MaternalRecord[];
  labResults?: LabResult[];
  medications?: Medication[];
  medicalHistoryEntries?: MedicalHistoryEntry[];
  referrals?: Referral[];
  consents?: Consent[];
  documents?: ClinicalDocument[];
  cases?: Case[];
  _count?: { encounters?: number };
}

export interface VitalSign {
  id: string;
  encounterId: string;
  systolic?: number | null;
  diastolic?: number | null;
  temperature?: number | null;
  heartRate?: number | null;
  respiratoryRate?: number | null;
  weight?: number | null;
  height?: number | null;
  bmi?: number | null;
  oxygenSat?: number | null;
}

export interface Diagnosis {
  id: string;
  encounterId: string;
  diseaseId?: string | null;
  icd10Code?: string | null;
  description: string;
  certainty: DiagnosisCertainty;
  isPrimary: boolean;
  disease?: Disease | null;
}

export interface PrescriptionItem {
  drug: string;
  dose?: string | null;
  frequency?: string | null;
  duration?: string | null;
  instructions?: string | null;
}

export interface Prescription {
  id: string;
  encounterId: string;
  items: PrescriptionItem[];
  notes?: string | null;
  createdAt?: string;
}

export interface Encounter {
  id: string;
  patientId: string;
  barangayId?: string | null;
  facilityId?: string | null;
  facility?: Facility | null;
  clinicianId?: string | null;
  type: EncounterType;
  encounterDate: string;
  chiefComplaint?: string | null;
  subjective?: string | null;
  objective?: string | null;
  assessment?: string | null;
  plan?: string | null;
  createdAt?: string;
  patient?: Patient;
  barangay?: Barangay | null;
  clinician?: Pick<User, 'id' | 'firstName' | 'lastName' | 'role'> | null;
  vitalSign?: VitalSign | null;
  diagnoses?: Diagnosis[];
  prescriptions?: Prescription[];
}

export interface Allergy {
  id: string;
  patientId: string;
  substance: string;
  reaction?: string | null;
  severity?: AllergySeverity | null;
  createdAt?: string;
}

export interface Problem {
  id: string;
  patientId: string;
  name: string;
  status: ProblemStatus;
  onsetDate?: string | null;
  resolvedAt?: string | null;
  notes?: string | null;
  createdAt?: string;
}

export interface Immunization {
  id: string;
  patientId: string;
  vaccine: string;
  doseNumber?: number | null;
  dateGiven: string;
  nextDueDate?: string | null;
  administeredBy?: string | null;
  notes?: string | null;
  createdAt?: string;
}

export interface MaternalRecord {
  id: string;
  patientId: string;
  lmp?: string | null;
  edd?: string | null;
  gravida?: number | null;
  para?: number | null;
  prenatalVisit?: number | null;
  visitDate: string;
  notes?: string | null;
  createdAt?: string;
}

export interface LabResult {
  id: string;
  patientId: string;
  encounterId?: string | null;
  testName: string;
  loincCode?: string | null;
  status?: LabStatus;
  value?: string | null;
  unit?: string | null;
  referenceRange?: string | null;
  orderedAt?: string | null;
  resultDate: string;
  notes?: string | null;
  createdAt?: string;
}

export interface Medication {
  id: string;
  patientId: string;
  encounterId?: string | null;
  drug: string;
  dose?: string | null;
  frequency?: string | null;
  route?: string | null;
  status: MedicationStatus;
  startDate: string;
  endDate?: string | null;
  notes?: string | null;
  createdAt?: string;
}

export interface MedicalHistoryEntry {
  id: string;
  patientId: string;
  category: MedicalHistoryCategory;
  description: string;
  notes?: string | null;
  createdAt?: string;
}

export interface Icd10Entry {
  code: string;
  description: string;
  diseaseCode?: string;
}

// ---------------------------------------------------------------------------
// EHR (municipality-wide) types
// ---------------------------------------------------------------------------
export type FacilityType =
  | 'RHU_MAIN'
  | 'BARANGAY_HEALTH_STATION'
  | 'MUNICIPAL_HOSPITAL'
  | 'DISTRICT_HOSPITAL'
  | 'PRIVATE_CLINIC'
  | 'LABORATORY'
  | 'PHARMACY';
export type ReferralStatus = 'REQUESTED' | 'ACCEPTED' | 'COMPLETED' | 'REJECTED';
export type ReferralPriority = 'ROUTINE' | 'URGENT' | 'EMERGENCY';
export type ConsentPurpose = 'TREATMENT' | 'EMERGENCY' | 'PUBLIC_HEALTH';
export type ConsentScope = 'SUMMARY' | 'FULL';
export type ConsentStatus = 'ACTIVE' | 'REVOKED';

export interface Facility {
  id: string;
  name: string;
  code: string;
  type: FacilityType;
  barangayId?: string | null;
  address?: string | null;
  contactNumber?: string | null;
  isActive: boolean;
  barangay?: Barangay | null;
  _count?: { users?: number; encounters?: number; patients?: number };
}

export interface Referral {
  id: string;
  patientId: string;
  fromFacilityId: string;
  toFacilityId: string;
  encounterId?: string | null;
  reason: string;
  clinicalSummary?: string | null;
  priority: ReferralPriority;
  status: ReferralStatus;
  resolvedAt?: string | null;
  createdAt?: string;
  patient?: Pick<Patient, 'id' | 'patientCode' | 'firstName' | 'lastName' | 'birthDate' | 'sex'>;
  fromFacility?: Facility;
  toFacility?: Facility;
}

export interface Consent {
  id: string;
  patientId: string;
  grantedToFacilityId?: string | null;
  purpose: ConsentPurpose;
  scope: ConsentScope;
  status: ConsentStatus;
  validFrom: string;
  validTo?: string | null;
  createdAt?: string;
  grantedToFacility?: Facility | null;
}

export interface ClinicalDocument {
  id: string;
  patientId: string;
  encounterId?: string | null;
  facilityId?: string | null;
  type: 'LAB_REPORT' | 'REFERRAL_LETTER' | 'DISCHARGE_SUMMARY' | 'IMAGING' | 'OTHER';
  title: string;
  format: 'PDF' | 'IMAGE' | 'TEXT' | 'FHIR';
  url?: string | null;
  content?: string | null;
  createdAt?: string;
}

export interface TerminologyConcept {
  id: string;
  system: 'ICD10' | 'LOINC' | 'SNOMED' | 'ATC';
  code: string;
  display: string;
  diseaseCode?: string | null;
}
