import { Router } from 'express';
import authRouter from './modules/auth/auth.router';
import userRouter from './modules/user/user.router';
import barangayRouter from './modules/barangay/barangay.router';
import diseaseRouter from './modules/disease/disease.router';
import caseRouter from './modules/case/case.router';
import riskReportRouter from './modules/risk-report/risk-report.router';
import alertRouter from './modules/alert/alert.router';
import feedbackRouter from './modules/feedback/feedback.router';
import predictionRouter from './modules/prediction/prediction.router';
import dashboardRouter from './modules/dashboard/dashboard.router';
import exportRouter from './modules/export/export.router';
import publicRouter from './modules/public/public.router';
import patientRouter from './modules/patient/patient.router';
import encounterRouter from './modules/encounter/encounter.router';
import immunizationRouter from './modules/immunization/immunization.router';
import maternalRouter from './modules/maternal/maternal.router';
import labRouter from './modules/lab/lab.router';
import clinicalRouter from './modules/clinical/clinical.router';
import facilityRouter from './modules/facility/facility.router';
import referralRouter from './modules/referral/referral.router';
import consentRouter from './modules/consent/consent.router';
import documentRouter from './modules/document/document.router';
import terminologyRouter from './modules/terminology/terminology.router';
import fhirRouter from './modules/fhir/fhir.router';
import hieRouter from './modules/hie/hie.router';
import portalRouter from './modules/portal/portal.router';

const router = Router();

router.get('/health', (_req, res) => {
  res.json({ success: true, message: 'ok', data: { timestamp: new Date().toISOString() } });
});

router.use('/auth', authRouter);
router.use('/users', userRouter);
router.use('/barangays', barangayRouter);
router.use('/diseases', diseaseRouter);
router.use('/cases', caseRouter);
router.use('/reports', riskReportRouter);
router.use('/alerts', alertRouter);
router.use('/feedback', feedbackRouter);
router.use('/predictions', predictionRouter);
router.use('/dashboard', dashboardRouter);
router.use('/exports', exportRouter);
router.use('/public', publicRouter);
router.use('/patients', patientRouter);
router.use('/encounters', encounterRouter);
router.use('/immunizations', immunizationRouter);
router.use('/maternal', maternalRouter);
router.use('/labs', labRouter);
router.use('/clinical', clinicalRouter);
router.use('/facilities', facilityRouter);
router.use('/referrals', referralRouter);
router.use('/consents', consentRouter);
router.use('/documents', documentRouter);
router.use('/terminology', terminologyRouter);
router.use('/fhir', fhirRouter);
router.use('/hie', hieRouter);
router.use('/portal', portalRouter);

export default router;
