import { caseRepository } from './case.repository';
import { diseaseRepository } from '../disease/disease.repository';
import { earlyWarningService } from '../early-warning/early-warning.service';
import { ageFromBirthDate, ageGroupFromAge } from '../../helper/age';
import { prisma } from '../../configuration/prisma';

/** Fire-and-forget early warning recheck. */
function scheduleEarlyWarning(barangayId: string, diseaseId: string): void {
  setImmediate(() => {
    void earlyWarningService.runCheck(barangayId, diseaseId);
  });
}

interface PatientContext {
  id: string;
  birthDate: Date;
  sex: string | null;
  barangayId: string | null;
}

type CaseCertainty = 'SUSPECTED' | 'PROBABLE' | 'CONFIRMED';

interface DiagnosisInput {
  diseaseId?: string;
  certainty: CaseCertainty;
}

const CERTAINTY_RANK: Record<CaseCertainty, number> = {
  SUSPECTED: 0,
  PROBABLE: 1,
  CONFIRMED: 2,
};

/** Pick the higher certainty when merging an encounter diagnosis with an existing case. */
function resolveCaseStatus(current: string | undefined, diagnosisCertainty: CaseCertainty): CaseCertainty {
  if (!current || !(current in CERTAINTY_RANK)) return diagnosisCertainty;
  const existing = current as CaseCertainty;
  return CERTAINTY_RANK[diagnosisCertainty] > CERTAINTY_RANK[existing]
    ? diagnosisCertainty
    : existing;
}

/** Find an ongoing surveillance case for the same patient and disease. */
export async function findOngoingCase(patientId: string, diseaseId: string) {
  return prisma.case.findFirst({
    where: {
      patientId,
      diseaseId,
      outcome: 'ONGOING',
    },
  });
}

/**
 * Create a SUSPECTED case when a notifiable disease is selected at patient registration.
 * Skips if an ongoing case already exists for the same patient + disease.
 */
export async function createSuspectedFromRegistration(
  patient: PatientContext,
  diseaseId: string,
  reportedBy: string
): Promise<void> {
  if (!patient.barangayId) return;

  const disease = await diseaseRepository.findById(diseaseId);
  if (!disease || !disease.isNotifiable || !disease.isActive) return;

  const existing = await findOngoingCase(patient.id, diseaseId);
  if (existing) return;

  const age = ageFromBirthDate(patient.birthDate);
  const ageGroup = ageGroupFromAge(age);

  await caseRepository.create({
    disease: { connect: { id: diseaseId } },
    barangay: { connect: { id: patient.barangayId } },
    reporter: { connect: { id: reportedBy } },
    patient: { connect: { id: patient.id } },
    autoGenerated: true,
    dateReported: new Date(),
    age,
    ageGroup,
    sex: patient.sex ?? undefined,
    status: 'SUSPECTED',
    outcome: 'ONGOING',
    source: 'RHU',
    notes: 'Auto-generated from patient registration.',
  });

  scheduleEarlyWarning(patient.barangayId, diseaseId);
}

/**
 * Upsert a surveillance case from a notifiable encounter diagnosis.
 * Creates a case at the diagnosis certainty level, or upgrades an existing ongoing case.
 */
export async function upsertCaseFromEncounter(params: {
  patient: PatientContext;
  diagnosis: DiagnosisInput;
  encounterId: string;
  encounterDate: Date;
  facilityId: string | null;
  reportedBy: string;
  skipIfEncounterCaseExists?: boolean;
}): Promise<void> {
  const { patient, diagnosis, encounterId, encounterDate, facilityId, reportedBy, skipIfEncounterCaseExists } =
    params;

  if (!patient.barangayId) return;
  if (!diagnosis.diseaseId) return;

  const disease = await diseaseRepository.findById(diagnosis.diseaseId);
  if (!disease || !disease.isNotifiable || !disease.isActive) return;

  if (skipIfEncounterCaseExists) {
    const existingFromEncounter = await caseRepository.findBySourceEncounterId(encounterId);
    if (existingFromEncounter) return;
  }

  const age = ageFromBirthDate(patient.birthDate, encounterDate);
  const ageGroup = ageGroupFromAge(age);
  const status = diagnosis.certainty;

  const ongoing = await findOngoingCase(patient.id, diagnosis.diseaseId);

  if (ongoing) {
    const nextStatus = resolveCaseStatus(ongoing.status, status);
    const upgraded = nextStatus !== ongoing.status;
    await caseRepository.update(ongoing.id, {
      status: nextStatus,
      sourceEncounterId: encounterId,
      dateReported: encounterDate,
      age,
      ageGroup,
      sex: patient.sex ?? undefined,
      facilityId: facilityId ?? undefined,
      notes: upgraded
        ? `Upgraded to ${nextStatus} from EMR encounter ${encounterId}.`
        : `Linked to EMR encounter ${encounterId}.`,
    });
  } else {
    await caseRepository.create({
      disease: { connect: { id: diagnosis.diseaseId } },
      barangay: { connect: { id: patient.barangayId } },
      reporter: { connect: { id: reportedBy } },
      patient: { connect: { id: patient.id } },
      sourceEncounterId: encounterId,
      facilityId: facilityId ?? undefined,
      autoGenerated: true,
      dateReported: encounterDate,
      age,
      ageGroup,
      sex: patient.sex ?? undefined,
      status,
      outcome: 'ONGOING',
      source: 'RHU',
      notes: `Auto-generated from EMR encounter ${encounterId}.`,
    });
  }

  scheduleEarlyWarning(patient.barangayId, diagnosis.diseaseId);
}

/** Process all diagnoses from an encounter and upsert surveillance cases. */
export async function generateCasesFromEncounterDiagnoses(params: {
  diagnoses: DiagnosisInput[];
  patient: PatientContext;
  barangayId: string | null;
  facilityId: string | null;
  encounterId: string;
  encounterDate: Date;
  reportedBy: string;
  skipIfEncounterCaseExists?: boolean;
}): Promise<void> {
  const patient = { ...params.patient, barangayId: params.barangayId ?? params.patient.barangayId };
  if (!patient.barangayId) return;

  for (const dx of params.diagnoses) {
    await upsertCaseFromEncounter({
      patient,
      diagnosis: dx,
      encounterId: params.encounterId,
      encounterDate: params.encounterDate,
      facilityId: params.facilityId,
      reportedBy: params.reportedBy,
      skipIfEncounterCaseExists: params.skipIfEncounterCaseExists,
    });
  }
}
